//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.1433
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetEmote {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Icons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Icons() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetEmote.Icons", typeof(Icons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Druid_CatForm {
            get {
                object obj = ResourceManager.GetObject("Ability_Druid_CatForm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Druid_ChallangingRo {
            get {
                object obj = ResourceManager.GetObject("Ability_Druid_ChallangingRo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Druid_DemoralizingR {
            get {
                object obj = ResourceManager.GetObject("Ability_Druid_DemoralizingR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Bat {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Bat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Bear {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Bear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Boar {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Boar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Cat {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Cat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Crab {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Crab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Crocolis {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Crocolis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_DragonHa {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_DragonHa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Gorilla {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Gorilla", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Hyena {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Hyena", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_NetherRa {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_NetherRa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Owl {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Owl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Raptor {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Raptor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Ravager {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Ravager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Scorpid {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Scorpid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Serpent {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Serpent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Spider {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Spider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Sporebat {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Sporebat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_TallStri {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_TallStri", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Turtle {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Turtle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Vulture {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Vulture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_WarpStal {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_WarpStal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_WindSerp {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_WindSerp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Wolf {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Wolf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AddChildNode {
            get {
                object obj = ResourceManager.GetObject("AddChildNode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AddConfiguration {
            get {
                object obj = ResourceManager.GetObject("AddConfiguration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AddNode {
            get {
                object obj = ResourceManager.GetObject("AddNode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Condition {
            get {
                object obj = ResourceManager.GetObject("Condition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImportConfiguration {
            get {
                object obj = ResourceManager.GetObject("ImportConfiguration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap INV_Letter_01 {
            get {
                object obj = ResourceManager.GetObject("INV_Letter_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap INV_Misc_Book_02 {
            get {
                object obj = ResourceManager.GetObject("INV_Misc_Book_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap INV_Misc_PunchCards_Blue {
            get {
                object obj = ResourceManager.GetObject("INV_Misc_PunchCards_Blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap INV_Misc_PunchCards_Prismat {
            get {
                object obj = ResourceManager.GetObject("INV_Misc_PunchCards_Prismat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap INV_Misc_PunchCards_Red {
            get {
                object obj = ResourceManager.GetObject("INV_Misc_PunchCards_Red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap INV_Misc_PunchCards_White {
            get {
                object obj = ResourceManager.GetObject("INV_Misc_PunchCards_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap INV_Misc_PunchCards_Yellow {
            get {
                object obj = ResourceManager.GetObject("INV_Misc_PunchCards_Yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap INV_Misc_QuestionMark {
            get {
                object obj = ResourceManager.GetObject("INV_Misc_QuestionMark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap INV_Misc_Rune_01 {
            get {
                object obj = ResourceManager.GetObject("INV_Misc_Rune_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap INV_Misc_Spyglass_03 {
            get {
                object obj = ResourceManager.GetObject("INV_Misc_Spyglass_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap INV_Musket_02 {
            get {
                object obj = ResourceManager.GetObject("INV_Musket_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap INV_Weapon_Bow_07 {
            get {
                object obj = ResourceManager.GetObject("INV_Weapon_Bow_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Load {
            get {
                object obj = ResourceManager.GetObject("Load", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Options {
            get {
                object obj = ResourceManager.GetObject("Options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RemoveConfiguration {
            get {
                object obj = ResourceManager.GetObject("RemoveConfiguration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RemoveNode {
            get {
                object obj = ResourceManager.GetObject("RemoveNode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spell_ChargeNegative {
            get {
                object obj = ResourceManager.GetObject("Spell_ChargeNegative", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spell_ChargePositive {
            get {
                object obj = ResourceManager.GetObject("Spell_ChargePositive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spell_Nature_Drowsy {
            get {
                object obj = ResourceManager.GetObject("Spell_Nature_Drowsy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spell_Shadow_SummonFelGuard {
            get {
                object obj = ResourceManager.GetObject("Spell_Shadow_SummonFelGuard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spell_Shadow_SummonFelHunte {
            get {
                object obj = ResourceManager.GetObject("Spell_Shadow_SummonFelHunte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spell_Shadow_SummonImp {
            get {
                object obj = ResourceManager.GetObject("Spell_Shadow_SummonImp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spell_Shadow_SummonInfernal {
            get {
                object obj = ResourceManager.GetObject("Spell_Shadow_SummonInfernal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spell_Shadow_SummonSuccubus {
            get {
                object obj = ResourceManager.GetObject("Spell_Shadow_SummonSuccubus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spell_Shadow_SummonVoidWalk {
            get {
                object obj = ResourceManager.GetObject("Spell_Shadow_SummonVoidWalk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
