//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.1433
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetEmote.Graphics {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IconsWoW {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IconsWoW() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetEmote.Graphics.IconsWoW", typeof(IconsWoW).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Druid_PrimalPrecision {
            get {
                object obj = ResourceManager.GetObject("Ability_Druid_PrimalPrecision", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Bat {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Bat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Bear {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Bear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Boar {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Boar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Cat {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Cat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Chimera {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Chimera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_CoreHound {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_CoreHound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Crab {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Crab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Crocolisk {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Crocolisk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Devilsaur {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Devilsaur", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_DragonHawk {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_DragonHawk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Gorilla {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Gorilla", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Hyena {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Hyena", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Moth {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Moth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_NetherRay {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_NetherRay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Owl {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Owl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Raptor {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Raptor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Ravager {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Ravager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Rhino {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Rhino", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Scorpid {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Scorpid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Silithid {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Silithid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Spider {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Spider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Sporebat {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Sporebat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_TallStrider {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_TallStrider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Turtle {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Turtle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Vulture {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Vulture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_WarpStalker {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_WarpStalker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Wasp {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Wasp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_WindSerpent {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_WindSerpent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Wolf {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Wolf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ability_Hunter_Pet_Worm {
            get {
                object obj = ResourceManager.GetObject("Ability_Hunter_Pet_Worm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap INV_Misc_QuestionMark {
            get {
                object obj = ResourceManager.GetObject("INV_Misc_QuestionMark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap INV_Weapon_Bow_07 {
            get {
                object obj = ResourceManager.GetObject("INV_Weapon_Bow_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spell_Nature_Drowsy {
            get {
                object obj = ResourceManager.GetObject("Spell_Nature_Drowsy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spell_Nature_GuardianWard {
            get {
                object obj = ResourceManager.GetObject("Spell_Nature_GuardianWard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spell_Shadow_SummonFelGuard {
            get {
                object obj = ResourceManager.GetObject("Spell_Shadow_SummonFelGuard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spell_Shadow_SummonFelHunter {
            get {
                object obj = ResourceManager.GetObject("Spell_Shadow_SummonFelHunter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spell_Shadow_SummonImp {
            get {
                object obj = ResourceManager.GetObject("Spell_Shadow_SummonImp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spell_Shadow_SummonInfernal {
            get {
                object obj = ResourceManager.GetObject("Spell_Shadow_SummonInfernal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spell_Shadow_SummonSuccubus {
            get {
                object obj = ResourceManager.GetObject("Spell_Shadow_SummonSuccubus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spell_Shadow_SummonVoidWalker {
            get {
                object obj = ResourceManager.GetObject("Spell_Shadow_SummonVoidWalker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
